--
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "db/**/*"
  - "config/**/*"
  - "bin/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: ["lib"]
plugins:
  - solargraph-rails
max_files: 5000
completion:
  visibility: "private"

