--
include:
  - "**/*.rb"
bundler: true
exclude:
  - "log/**/*"
  - "tmp/**/*"
  - "node_modules/**/*"
  - "db/schema.rb"
  - "db/migrate/**/*"
  - ".git/**/*"
  - "coverage/**/*"
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: ["lib"]
plugins:
  - solargraph-rails
max_files: 5000
completion:
  visibility: "private"

